version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ea-wq-incident-web:
    build:
      target: development
    image: ea-wq-incident-web-development
    container_name: ea-wq-incident-web-test
    command: npm run test
    environment: 
      NODE_ENV: test
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
